# Generated by Django 3.0.4 on 2020-03-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homewins', '0002_auto_20200322_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latlong',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='ssid',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
